### ISSUE TITLE
能解释一下这个切图参数怎么来的吗？

### ISSUE THREAD

**Issue by brianlaibaoqin** [tonglei100/look#1]
![image](https://user-images.githubusercontent.com/34622645/61443860-e4bad880-a97c-11e9-8f81-2586719c354d.png)

**Comment by tonglei100** [comment]
用画图工具打开验证码，找到能把4个字符等分切割的坐标
box 的每个元素为左上坐标及右下坐标，如box[0]的 9,3是第一个等分切割左上坐标，24,30是右下坐标

**Comment by brianlaibaoqin** [comment]
能说一下，用什么切图工具。

**Comment by tonglei100** [comment]
Windows 自带的画图板...
