### ISSUE TITLE
看了look_example我搞懂了怎么使用，就是pip 安装以后还是不能直接在他人项目代码直接使用

### ISSUE THREAD

**Issue by brianlaibaoqin** [tonglei100/look#2]
建议在readme优化一下说明介绍：
1.描述一下怎么切图，box的参数介绍。
2.怎么训练模型，图片的存放目录
3.pip安装后，怎么快速在一个项目中应用look 。最好有简单的实例代码（我刚开始不知道怎么在自己的项目中使用，看了两天代码，摸清楚图片存放的目录结构，东改西改的才终于用上了，笑哭 哭笑 笑出眼泪 破涕为笑 笑死 笑尿 笑cry）。

**Comment by tonglei100** [comment]
后续有空考虑加一下
你有心也可以写一篇文章介绍...
