### ISSUE TITLE
train时报RuntimeError: size mismatch THTensorMath.cpp:961 错误，帮忙看一下啊

### ISSUE THREAD

**Issue by mindsheng** [tonglei100/look#3]
执行 train('model.pkl')  时报错了：

C:\Python36\python.exe E:/pythonworkspaces/look-master/look/start.py
init net
Traceback (most recent call last):
  File "E:/pythonworkspaces/look-master/look/start.py", line 40, in <module>
    train('model.pkl')
  File "C:\Python36\lib\site-packages\look\captcha.py", line 26, in train
    predict_labels = cnn(images)
  File "C:\Python36\lib\site-packages\torch\nn\modules\module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "C:\Python36\lib\site-packages\look\cnn_model.py", line 39, in forward
    out = self.fc(out)
  File "C:\Python36\lib\site-packages\torch\nn\modules\module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "C:\Python36\lib\site-packages\torch\nn\modules\container.py", line 92, in forward
    input = module(input)
  File "C:\Python36\lib\site-packages\torch\nn\modules\module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "C:\Python36\lib\site-packages\torch\nn\modules\linear.py", line 92, in forward
    return F.linear(input, self.weight, self.bias)
  File "C:\Python36\lib\site-packages\torch\nn\functional.py", line 1406, in linear
    ret = torch.addmm(bias, input, weight.t())
RuntimeError: size mismatch, m1: [64 x 768], m2: [960 x 1024] at ..\aten\src\TH/generic/THTensorMath.cpp:961

我的setting文件内容：
from pathlib import Path

NUMBER = ['1','2', '3', '4', '5', '6', '7', '8', '9']
ALPHABET = ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K',
            'L', 'M', 'N', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z']

ALL_CHAR_SET = NUMBER + ALPHABET
ALL_CHAR_SET_LEN = len(ALL_CHAR_SET)
MAX_CAPTCHA = 1

# 图像大小
IMAGE_HEIGHT = 42
IMAGE_WIDTH = 31

# 切图参数，图片大小要一致
box = {}
#(x, y, x + w, y + h)
box[0] = (1,3,31,42)
box[1] = (31,3,61,42)
box[2] = (62,3,92,42)
box[3] = (93,3,123,42)

LOOK_PATH = Path('.')
DATASET_PATH = LOOK_PATH / 'dataset'
MODEL_PATH = LOOK_PATH / 'model'                   # 模型目录
SOURCE_TRAIN_PATH = DATASET_PATH / 'source_train'  # 原始训练图集
SOURCE_TEST_PATH = DATASET_PATH / 'source_test'    # 原始测试图集
TRAIN_PATH = DATASET_PATH / 'train'                # 训练图集
TEST_PATH = DATASET_PATH / 'test'                  # 测试图集
CAPTCHA_PATH = DATASET_PATH / 'captcha'            # 验证码图片，可以为切图
DOWNLOAD_PATH = DATASET_PATH / 'download'          # 要识别的验证码存放目录

# Hyper Parameters
TRAIN_NUM_EPOCHS = 100
# TRAIN_BATCH_SIZE = 64
TRAIN_LEARNING_RATE = 0.001

不知道什么原因啊！网上资料又太少了！！大神帮看看吧！

**Comment by mindsheng** [comment]
torch version:
![image](https://user-images.githubusercontent.com/16882452/62536873-acbefb00-b881-11e9-8f91-dd26232b77b1.png)

**Comment by mindsheng** [comment]
torch version:
torch                 1.1.0
torchvision           0.3.0

有空帮看看啊

**Comment by tonglei100** [comment]
可能是长和宽定义不对，改为下面的试试
IMAGE_HEIGHT = 39
IMAGE_WIDTH = 30

**Comment by mindsheng** [comment]
> 可能是长和宽定义不对，改为下面的试试
> IMAGE_HEIGHT = 39
> IMAGE_WIDTH = 30

改了后，再训练，就可以了，但是我的切图后的单个图片大小就是31*42，要比原图小一些吗？不太懂哈

**Comment by tonglei100** [comment]
按 box 写的应该就是 39，30
小了好像可以，大了不行
